stages:
  generate_data:
    cmd: python -m src.stages.00_generate_data --params params.yaml
    deps:
      - src/stages/00_generate_data.py
      - params.yaml
    outs:
      - data/raw/brake_sensor_data.csv

  split:
    cmd: python -m src.stages.01_split --params params.yaml
    deps:
      - src/stages/01_split.py
      - data/raw/brake_sensor_data.csv
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  features:
    cmd: python -m src.stages.02_features --params params.yaml
    deps:
      - src/stages/02_features.py
      - data/processed/train.csv
      - data/processed/test.csv
      - params.yaml
    outs:
      - data/processed/X_train.npy
      - data/processed/y_train.npy
      - data/processed/X_test.npy
      - data/processed/y_test.npy
      - artifacts/preprocess.joblib

    train:
    cmd: python -m src.stages.03_train --params params.yaml
    deps:
      - src/stages/03_train.py
      - data/processed/X_train.npy
      - data/processed/y_train.npy
    outs:
      - artifacts/model.joblib


  evaluate:
    cmd: python -m src.stages.04_evaluate --params params.yaml
    deps:
      - src/stages/04_evaluate.py
      - models/model.pkl
      - data/processed/X_test.npy
      - data/processed/y_test.npy
      - params.yaml
    metrics:
      - evaluation.json
