name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint import
        run: python - <<'PY'
import sys, pkgutil
print("Python OK. Installed:", [m.name for m in pkgutil.iter_modules()][:5])
PY
      - name: Dry run pipeline (generate small sample)
        env:
          DVC_NO_ANALYTICS: "true"
        run: |
          python - <<'PY'
import yaml
p = yaml.safe_load(open('params.yaml'))
p["data"]["n_samples"]=1000
open('params.yaml','w').write(yaml.safe_dump(p, sort_keys=False))
print("Shrunk n_samples for CI")
PY
          dvc repro
